<?xml version="1.0" encoding="utf-8"?><Database Name="QLDPKS" Class="QLDPKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=QLDPKS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLDPKSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BANGLOC" Member="BANGLOCs">
    <Type Name="BANGLOC">
      <Column Name="IDBANG" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENBANG" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="BANGLOC_OPTIONLOC" Member="OPTIONLOCs" ThisKey="IDBANG" OtherKey="IDBANG" Type="OPTIONLOC" />
    </Type>
  </Table>
  <Table Name="dbo.TIENICH" Member="TIENICHes">
    <Type Name="TIENICH">
      <Column Name="IDTIENICH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTIENICH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ICON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TIENICH_KSTIENICH" Member="KSTIENICHes" ThisKey="IDTIENICH" OtherKey="IDTIENICH" Type="KSTIENICH" />
    </Type>
  </Table>
  <Table Name="dbo.BOOKING" Member="BOOKINGs">
    <Type Name="BOOKING">
      <Column Name="MABOOK" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MAKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYVAO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NGAYDI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="YEUCAU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="THANHTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SODEM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BOOKING_HOADON" Member="HOADONs" ThisKey="MABOOK" OtherKey="MABOOK" Type="HOADON" />
      <Association Name="PHONG_BOOKING" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
      <Association Name="TAIKHOAN_BOOKING" Member="TAIKHOAN" ThisKey="MAKH" OtherKey="MAKH" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MADV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDV" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="DICHVU_PHONGDV_FEE" Member="PHONGDV_FEEs" ThisKey="MADV" OtherKey="MADV" Type="PHONGDV_FEE" />
      <Association Name="DICHVU_PHONGDV_FREE" Member="PHONGDV_FREEs" ThisKey="MADV" OtherKey="MADV" Type="PHONGDV_FREE" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MAMANHINH" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_MAN_HINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MABOOK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="BOOKING_HOADON" Member="BOOKING" ThisKey="MABOOK" OtherKey="MABOOK" Type="BOOKING" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOME_DDNB" Member="HOME_DDNBs">
    <Type Name="HOME_DDNB">
      <Column Name="IDDIADIEM" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDIADIEM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="img" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="HOME_DDNB_KHACHSAN" Member="KHACHSANs" ThisKey="IDDIADIEM" OtherKey="IDDIADIEM" Type="KHACHSAN" />
    </Type>
  </Table>
  <Table Name="dbo.HOME_SLIDE" Member="HOME_SLIDEs">
    <Type Name="HOME_SLIDE">
      <Column Name="IDSLIDE" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SLIDECONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHSAN" Member="KHACHSANs">
    <Type Name="KHACHSAN">
      <Column Name="MAKHACHSAN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANCC" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENKHACHSAN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SOLUONGPHONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOSAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TINH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QUAN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PHUONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DUONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIACHICUTHE" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ANHKS1" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ANHKS2" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ANHKS3" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ANHKS4" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ANHKS5" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIADANH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DANHGIA" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIEM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IDDIADIEM" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="KHACHSAN_KSTIENICH" Member="KSTIENICHes" ThisKey="MAKHACHSAN" OtherKey="MAKHACHSAN" Type="KSTIENICH" />
      <Association Name="KHACHSAN_PHONG" Member="PHONGs" ThisKey="MAKHACHSAN" OtherKey="MAKHACHSAN" Type="PHONG" />
      <Association Name="HOME_DDNB_KHACHSAN" Member="HOME_DDNB" ThisKey="IDDIADIEM" OtherKey="IDDIADIEM" Type="HOME_DDNB" IsForeignKey="true" />
      <Association Name="NCC_KHACHSAN" Member="NCC" ThisKey="MANCC" OtherKey="MANCC" Type="NCC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KSTIENICH" Member="KSTIENICHes">
    <Type Name="KSTIENICH">
      <Column Name="MAKHACHSAN" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDTIENICH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KHACHSAN_KSTIENICH" Member="KHACHSAN" ThisKey="MAKHACHSAN" OtherKey="MAKHACHSAN" Type="KHACHSAN" IsForeignKey="true" />
      <Association Name="TIENICH_KSTIENICH" Member="TIENICH" ThisKey="IDTIENICH" OtherKey="IDTIENICH" Type="TIENICH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIPHONG" Member="LOAIPHONGs">
    <Type Name="LOAIPHONG">
      <Column Name="MALOAI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAIPHONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="LOAIPHONG_PHONG" Member="PHONGs" ThisKey="MALOAI" OtherKey="MALOAI" Type="PHONG" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MANCC" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NCC_KHACHSAN" Member="KHACHSANs" ThisKey="MANCC" OtherKey="MANCC" Type="KHACHSAN" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QUYEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANV" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.OPTIONLOC" Member="OPTIONLOCs">
    <Type Name="OPTIONLOC">
      <Column Name="IDKIEULOC" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKIEULOC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDBANG" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="BANGLOC_OPTIONLOC" Member="BANGLOC" ThisKey="IDBANG" OtherKey="IDBANG" Type="BANGLOC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG" Member="PHONGs">
    <Type Name="PHONG">
      <Column Name="MAKHACHSAN" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="MAPHONG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENPHONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIENTICH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANGCANH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIAM" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ANH1" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ANH2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ANH3" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ANH4" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ANH5" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SOGIUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOAIGIUONG" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOKHACH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHONG_BOOKING" Member="BOOKINGs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="BOOKING" />
      <Association Name="PHONG_PHONGDV_FEE" Member="PHONGDV_FEEs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONGDV_FEE" />
      <Association Name="PHONG_PHONGDV_FREE" Member="PHONGDV_FREEs" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONGDV_FREE" />
      <Association Name="KHACHSAN_PHONG" Member="KHACHSAN" ThisKey="MAKHACHSAN" OtherKey="MAKHACHSAN" Type="KHACHSAN" IsForeignKey="true" />
      <Association Name="LOAIPHONG_PHONG" Member="LOAIPHONG" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAIPHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGDV_FEE" Member="PHONGDV_FEEs">
    <Type Name="PHONGDV_FEE">
      <Column Name="MAPHONG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MADV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MADVFEE" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DICHVU_PHONGDV_FEE" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="PHONG_PHONGDV_FEE" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGDV_FREE" Member="PHONGDV_FREEs">
    <Type Name="PHONGDV_FREE">
      <Column Name="MAPHONG" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MADV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MADVFREE" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DICHVU_PHONGDV_FREE" Member="DICHVU" ThisKey="MADV" OtherKey="MADV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="PHONG_PHONGDV_FREE" Member="PHONG" ThisKey="MAPHONG" OtherKey="MAPHONG" Type="PHONG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNGNHOMNGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHANVIEN_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="NHANVIEN" ThisKey="TENDANGNHAP" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="QL_NHOM_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NHOM_NGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOM_NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOM_NGUOIDUNG" Member="QL_NHOM_NGUOIDUNGs">
    <Type Name="QL_NHOM_NGUOIDUNG">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NHOM_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="QL_NHOM_NGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="MANHOM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="DM_MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOM_NGUOIDUNG_QL_PHANQUYEN" Member="QL_NHOM_NGUOIDUNG" ThisKey="MANHOM" OtherKey="MANHOM" Type="QL_NHOM_NGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="MAKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDN" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Association Name="TAIKHOAN_BOOKING" Member="BOOKINGs" ThisKey="MAKH" OtherKey="MAKH" Type="BOOKING" />
    </Type>
  </Table>
</Database>