#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_dat_phong_ks.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDPKS")]
	public partial class QLDPKSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHOME_DDNB(HOME_DDNB instance);
    partial void UpdateHOME_DDNB(HOME_DDNB instance);
    partial void DeleteHOME_DDNB(HOME_DDNB instance);
    partial void InsertHOME_SLIDE(HOME_SLIDE instance);
    partial void UpdateHOME_SLIDE(HOME_SLIDE instance);
    partial void DeleteHOME_SLIDE(HOME_SLIDE instance);
    #endregion
		
		public QLDPKSDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLDPKSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDPKSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDPKSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDPKSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDPKSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<HOME_DDNB> HOME_DDNBs
		{
			get
			{
				return this.GetTable<HOME_DDNB>();
			}
		}
		
		public System.Data.Linq.Table<HOME_SLIDE> HOME_SLIDEs
		{
			get
			{
				return this.GetTable<HOME_SLIDE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOME_DDNB")]
	public partial class HOME_DDNB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDDIADIEM;
		
		private string _TENDIADIEM;
		
		private string _img;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDIADIEMChanging(string value);
    partial void OnIDDIADIEMChanged();
    partial void OnTENDIADIEMChanging(string value);
    partial void OnTENDIADIEMChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    #endregion
		
		public HOME_DDNB()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDIADIEM", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDDIADIEM
		{
			get
			{
				return this._IDDIADIEM;
			}
			set
			{
				if ((this._IDDIADIEM != value))
				{
					this.OnIDDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._IDDIADIEM = value;
					this.SendPropertyChanged("IDDIADIEM");
					this.OnIDDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDIADIEM", DbType="NVarChar(MAX)")]
		public string TENDIADIEM
		{
			get
			{
				return this._TENDIADIEM;
			}
			set
			{
				if ((this._TENDIADIEM != value))
				{
					this.OnTENDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._TENDIADIEM = value;
					this.SendPropertyChanged("TENDIADIEM");
					this.OnTENDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOME_SLIDE")]
	public partial class HOME_SLIDE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDSLIDE;
		
		private string _SLIDECONTENT;
		
		private string _IMG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSLIDEChanging(string value);
    partial void OnIDSLIDEChanged();
    partial void OnSLIDECONTENTChanging(string value);
    partial void OnSLIDECONTENTChanged();
    partial void OnIMGChanging(string value);
    partial void OnIMGChanged();
    #endregion
		
		public HOME_SLIDE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSLIDE", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSLIDE
		{
			get
			{
				return this._IDSLIDE;
			}
			set
			{
				if ((this._IDSLIDE != value))
				{
					this.OnIDSLIDEChanging(value);
					this.SendPropertyChanging();
					this._IDSLIDE = value;
					this.SendPropertyChanged("IDSLIDE");
					this.OnIDSLIDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLIDECONTENT", DbType="NVarChar(MAX)")]
		public string SLIDECONTENT
		{
			get
			{
				return this._SLIDECONTENT;
			}
			set
			{
				if ((this._SLIDECONTENT != value))
				{
					this.OnSLIDECONTENTChanging(value);
					this.SendPropertyChanging();
					this._SLIDECONTENT = value;
					this.SendPropertyChanged("SLIDECONTENT");
					this.OnSLIDECONTENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMG", DbType="NVarChar(MAX)")]
		public string IMG
		{
			get
			{
				return this._IMG;
			}
			set
			{
				if ((this._IMG != value))
				{
					this.OnIMGChanging(value);
					this.SendPropertyChanging();
					this._IMG = value;
					this.SendPropertyChanged("IMG");
					this.OnIMGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
