//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DOUBLESHIT;Initial Catalog=QLDPKS;Integrated Security=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=B902702E395D455\\WIN2K;Initial Catalog=QLDPKS;User ID=sa;Password=sa20" +
            "12")]
>>>>>>> 471b3102bc25857bb13ca30876b7ba2f7bcb9fcf
        public string QLDPKSConnectionString {
            get {
                return ((string)(this["QLDPKSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
<<<<<<< HEAD
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DOUBLESHIT;Initial Catalog=QLDPKS;Integrated Security=True")]
=======
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=B902702E395D455\\WIN2K;Initial Catalog=QLDPKS;User ID=sa;Password=sa20" +
            "12")]
>>>>>>> 471b3102bc25857bb13ca30876b7ba2f7bcb9fcf
        public string QLDPKSConnectionString1 {
            get {
                return ((string)(this["QLDPKSConnectionString1"]));
            }
        }
<<<<<<< HEAD
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DOUBLESHIT;Initial Catalog=QLDPKS;Integrated Security=True")]
        public string QLDPKSConnectionString2 {
            get {
                return ((string)(this["QLDPKSConnectionString2"]));
            }
        }
=======
>>>>>>> 471b3102bc25857bb13ca30876b7ba2f7bcb9fcf
    }
}
